[package]
name = "coinstr"
version = "0.1.0"
edition = "2021"
description.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
readme = "../README.md"
keywords.workspace = true

[dependencies]
async-stream = "0.3"
coinstr-common = { version = "0.1", path = "../coinstr-common" }
coinstr-core = { version = "0.1", path = "../coinstr-core" }
env_logger = "0.10"
iced = { version = "0.9", default-features = false, features = ["image", "glow", "qr_code", "svg", "tokio"] }
iced_futures = "0.6"
iced_lazy = "0.6"
iced_native = "0.10"
log = "0.4"
once_cell = "1.17"
rfd = "0.11"
tokio = { version = "1", features = ["full"] }
