[package]
name = "coinstr"
version = "0.1.0"
edition = "2021"

[dependencies]
# nostr_rust = "*"
log = "0.4"
serde_json = "*"
# secp256k1 = { version = "0.25", features = ["bitcoin_hashes", "global-context", "rand-std"] }
bdk = { version = "0.27.0", default-features = false, features = ["compiler", "all-keys", "use-esplora-reqwest", "esplora"] }
clap = { features = ["cargo", "derive"], version="4.1.1" }
rand = "*"
bitcoin = "0.29.2"
# bip39 = "1.0.1"
# rust-bip39 = "*"
rand_core = "*"
miniscript = { version = "9.0", features = ["serde"] }
nostr-sdk = { version = "0.18.0", features = ["blocking", "all-nips"] }
nostr =  { version = "0.18.0", features = ["blocking", "all-nips"] }
config = "0.13.3"
anyhow = "1.0.69"
# lazy_static = "*"
termtree = "*"

[dev-dependencies]
assert_matches = "1.5.0"