[package]
name = "coinstr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nostr_rust = "*"
log = "0.4"
serde_json = "*"
secp256k1 = { version = "0.26", features = ["bitcoin_hashes", "global-context", "rand-std"] }
bdk = { version = "0.26.0", default-feature = false, features = ["all-keys"] }