[workspace]
members = [
    "bindings/coinstr-sdk-ffi",
    "crates/coinstr",
    "crates/coinstr-cli",
    "crates/coinstr-common",
    "crates/coinstr-core",
    "crates/coinstr-sdk",
]
default-members = ["crates/coinstr", "crates/coinstr-cli"]
resolver = "2"

[workspace.package]
version = "0.3.0"
description = "Using nostr to coordinate Bitcoin spending policy signatures and multi-custody"
authors = ["Yuki Kishimoto <yukikishimoto@protonmail.com>", "Max Gravitt"]
homepage = "https://github.com/coinstr/coinstr"
repository = "https://github.com/coinstr/coinstr.git"
license = "MIT"
keywords = ["coinstr", "bitcoin", "nostr"]

[workspace.dependencies]
once_cell = "1.18"
serde = "=1.0.171"
tracing = "0.1"

[patch.crates-io]
electrum-client = { git = "https://github.com/yukibtc/rust-electrum-client", rev = "ee2e522cb808ed17a8ded9811323dc480459c4ed" }

[profile.release]
lto = true
codegen-units = 1
panic = "abort"