[workspace]
members = [
    "bindings/coinstr-ffi",
    "crates/coinstr",
    "crates/coinstr-cli",
    "crates/coinstr-common",
    "crates/coinstr-core",
]
default-members = ["crates/coinstr", "crates/coinstr-cli"]
resolver = "2"

[workspace.package]
description = "Using nostr to coordinate Bitcoin spending policy signatures and multi-custody"
homepage = "https://github.com/coinstr/coinstr"
repository = "https://github.com/coinstr/coinstr.git"
license = "MIT"
keywords = ["coinstr", "bitcoin", "nostr"]

[profile.release]
lto = true
codegen-units = 1