[workspace]
members = [
    "bindings/coinstr-sdk-ffi",
    "crates/coinstr",
    "crates/coinstr-cli",
    "crates/coinstr-common",
    "crates/coinstr-core",
    "crates/coinstr-sdk",
    "crates/coinstr-sdk-manager",
]
default-members = ["crates/coinstr", "crates/coinstr-cli"]
resolver = "2"

[workspace.package]
version = "0.3.0"
description = "Using nostr to coordinate Bitcoin spending policy signatures and multi-custody"
authors = ["Yuki Kishimoto <yukikishimoto@protonmail.com>", "Max Gravitt"]
homepage = "https://github.com/coinstr/coinstr"
repository = "https://github.com/coinstr/coinstr.git"
license = "MIT"
keywords = ["coinstr", "bitcoin", "nostr"]

[profile.release]
lto = true
codegen-units = 1
strip = true
panic = "abort"