[workspace]
members = [
    "coinstr",
    "coinstr-cli",
    "coinstr-common",
    "coinstr-core",
]
default-members = ["coinstr", "coinstr-cli"]
resolver = "2"

[workspace.package]
description = "Using nostr to coordinate Bitcoin spending policy signatures and multi-custody"
homepage = "https://github.com/NostrDevKit/coinstr"
repository = "https://github.com/NostrDevKit/coinstr.git"
license = "MIT"
keywords = ["coinstr", "bitcoin", "nostr"]

[profile.release]
lto = true
codegen-units = 1