[package]
name = "smartvaults-sdk-ffi"
version.workspace = true
edition = "2021"
description = "Smart Vaults SDK FFI."
homepage.workspace = true
repository.workspace = true
license.workspace = true

[lib]
name = "smartvaults_sdk_ffi"
crate-type = ["cdylib", "staticlib"]
doctest = false

[dependencies]
async-utility = "0.1"
smartvaults-sdk = { path = "../../crates/smartvaults-sdk", features = ["blocking"] }
nostr-ffi = { git = "https://github.com/rust-nostr/nostr", rev = "840e20708f8350764c43ce5390e94b18f501f626" }
nostr-sdk-ffi = { git = "https://github.com/rust-nostr/nostr", rev = "840e20708f8350764c43ce5390e94b18f501f626" }
tokio = { workspace = true, features = ["rt-multi-thread"] }
tracing.workspace = true
uniffi.workspace = true
