[package]
name = "coinstr-sdk-ffi"
version = "0.1.0"
edition = "2021"
description = "Coinstr SDK FFI."
homepage.workspace = true
repository.workspace = true
license.workspace = true

[lib]
name = "coinstr_sdk_ffi"
crate-type = ["cdylib", "staticlib"]

[[bin]]
name = "uniffi-bindgen"
path = "uniffi-bindgen.rs"

[dependencies]
coinstr-sdk = { path = "../../crates/coinstr-sdk", features = ["blocking"] }
log = "0.4"
uniffi = { version = "0.24", features = ["cli"] }
uniffi_bindgen = "0.23"
uniffi_macros = "0.23"

[target.'cfg(target_os = "android")'.dependencies]
android_logger = "0.13"

[build-dependencies]
uniffi = { version = "0.24", features = ["build"] }
