[package]
name = "coinstr-sdk-ffi"
version.workspace = true
edition = "2021"
description = "Coinstr SDK FFI."
homepage.workspace = true
repository.workspace = true
license.workspace = true

[lib]
name = "coinstr_sdk_ffi"
crate-type = ["cdylib", "staticlib"]

[[bin]]
name = "uniffi-bindgen"
path = "uniffi-bindgen.rs"

[dependencies]
async-utility = "0.1"
coinstr-sdk = { path = "../../crates/coinstr-sdk", features = ["blocking"] }
nostr-ffi = { git = "https://github.com/rust-nostr/nostr", rev = "d523ba599a1e7aa52b98a29a310cabb1140b752b" }
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
uniffi = { version = "0.24", features = ["cli"] }

[build-dependencies]
uniffi = { version = "0.24", features = ["build"] }
