[package]
name = "coinstr-sdk-ffi"
version.workspace = true
edition = "2021"
description = "Coinstr SDK FFI."
homepage.workspace = true
repository.workspace = true
license.workspace = true

[lib]
name = "coinstr_sdk_ffi"
crate-type = ["cdylib", "staticlib"]

[[bin]]
name = "uniffi-bindgen"
path = "uniffi-bindgen.rs"

[dependencies]
async-utility = "0.1"
coinstr-sdk = { path = "../../crates/coinstr-sdk", features = ["blocking"] }
nostr-ffi = { git = "https://github.com/rust-nostr/nostr", rev = "be6c099de87ee6ede94ce83c5543ce5bca925dc6" }
tokio = { version = "1", features = ["full"] }
uniffi = { version = "0.24", features = ["cli"] }
uniffi_bindgen = "0.24"
uniffi_macros = "0.24"

[build-dependencies]
uniffi = { version = "0.24", features = ["build"] }
