[package]
name = "coinstr-sdk-ffi"
version.workspace = true
edition = "2021"
description = "Coinstr SDK FFI."
homepage.workspace = true
repository.workspace = true
license.workspace = true

[lib]
name = "coinstr_sdk_ffi"
crate-type = ["cdylib", "staticlib"]

[[bin]]
name = "uniffi-bindgen"
path = "uniffi-bindgen.rs"

[dependencies]
async-utility = "0.1"
coinstr-sdk = { path = "../../crates/coinstr-sdk", features = ["blocking"] }
log = "0.4"
nostr-ffi = { git = "https://github.com/rust-nostr/nostr", rev = "8ddeaaba6c0877cd6028d2b8005cd5ef04bbcd78" }
tokio = { version = "1", features = ["full"] }
uniffi = { version = "0.24", features = ["cli"] }
uniffi_bindgen = "0.24"
uniffi_macros = "0.24"

[target.'cfg(target_os = "android")'.dependencies]
android_logger = "0.13"

[build-dependencies]
uniffi = { version = "0.24", features = ["build"] }
