[bindings.kotlin]
package_name = "io.coinstr.sdk"
cdylib_name = "coinstr_sdk_ffi"

[bindings.swift]
ffi_module_filename = "coinstr_sdkFFI"
cdylib_name = "coinstr_sdk_ffi"

[bindings.python]
cdylib_name = "coinstr_sdk_ffi"
