[package]
name = "smartvaults-protocol"
edition = "2021"
version.workspace = true
description = "Implementation of the Smart Vaults protocol"
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
readme = "README.md"
keywords.workspace = true

[dependencies]
smartvaults-core = { path = "../smartvaults-core", default-features = false }
nostr = { git = "https://github.com/rust-nostr/nostr", rev = "36e39f47d7475ae741878cd3c11a83079d2bb0e4", default-features = false, features = ["std", "nip04"] }
serde = { workspace = true, features = ["derive"] }
serde_json = "1.0"
thiserror = { workspace = true }