[package]
name = "coinstr-sdk"
version.workspace = true
edition = "2021"
description = "Coinstr SDK"
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
readme = "README.md"
keywords.workspace = true

[features]
default = []
hwi = ["coinstr-core/hwi"]
blocking = ["async-utility/blocking", "nostr-sdk/blocking"]

[dependencies]
async-utility = "0.1"
bdk = { version = "0.28", default-features = false, features = ["std", "electrum", "sqlite-bundled"] }
coinstr-core = { path = "../coinstr-core" }
futures-util = "0.3"
nostr-sdk = { git = "https://github.com/rust-nostr/nostr", rev = "43e03513007ed799ba0335b4c897cb23f1259e39", default-features = false, features = ["nip04", "nip06", "nip19", "nip46"] }
parking_lot = "0.12"
r2d2 = "0.8"
r2d2_sqlite = "0.21"
rusqlite = { version = "0.28", features = ["bundled", "serde_json", "url"] }
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
tokio = { version = "1", features = ["sync"] }
tracing = "0.1"
tracing-appender = "0.2"
tracing-subscriber = "0.3"
