[package]
name = "coinstr-core"
version = "0.1.0"
edition = "2021"
description = "Coinstr's Core library."
homepage.workspace = true
repository.workspace = true
license.workspace = true
readme = "README.md"
keywords.workspace = true

[dependencies]
bdk = { version = "0.27", default-features = false, features = ["compiler", "electrum"] }
keechain-core = { git = "https://github.com/yukibtc/keechain", rev = "80f7ffd6d001dd67bf98b2d2d733685bceafff62", features = ["nostr"] }
nostr-sdk = { git = "https://github.com/rust-nostr/nostr", rev = "5419d6a93fec5c06202afbd77ee9d29c0bdc7996", default-features = false, features = ["blocking", "nip04", "nip06", "nip19"] }
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
