[package]
name = "coinstr-core"
version = "0.1.0"
edition = "2021"
description = "Coinstr's Core library."
homepage.workspace = true
repository.workspace = true
license.workspace = true
readme = "README.md"
keywords.workspace = true

[features]
default = []
blocking = ["nostr-sdk/blocking"]

[dependencies]
async-recursion = "1.0"
bdk = { version = "0.28", default-features = false, features = ["std", "compiler", "electrum", "sqlite-bundled"] }
bitcoinconsensus = "0.20.2-0.5.0"
futures-util = "0.3"
keechain-core = { git = "https://github.com/yukibtc/keechain", rev = "45309710e439294f57de03f4ef230b260fdd8c7a" }
log = "0.4"
nostr-sdk = { git = "https://github.com/rust-nostr/nostr", branch = "bitcoin-v0.29", default-features = false, features = ["nip04", "nip06", "nip19"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
tokio = { version = "1", features = ["sync"] }

[dev-dependencies]
tokio = { version = "1", features = ["macros"] }
