[package]
name = "coinstr-core"
version = "0.1.0"
edition = "2021"
description = "Coinstr's Core library."
homepage.workspace = true
repository.workspace = true
license.workspace = true
readme = "README.md"
keywords.workspace = true

[dependencies]
bdk = { version = "0.28", default-features = false, features = ["std", "compiler"] }
bitcoinconsensus = "0.20.2-0.5.0"
keechain-core = { git = "https://github.com/yukibtc/keechain", rev = "dd9a8bfddf99db7fe144f5eca3c4ea273610ef44" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
